### ISSUE TITLE
Add baseline settings for measles

### ISSUE THREAD

**Issue by AdrianListon** [s-andrews/virusbreak#12]
Measles example case baseline settings
4 days asymptomatic 
4 days symptomatic
0.3% death
90% infectious

Link to these articles below for references:
https://www.sciencedirect.com/science/article/pii/S0264410X16001717 
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC128813/

**Comment by s-andrews** [comment]
I've sent you an invite to be a collaborator on the project which means that you can edit the files in here (not that you're going to want to for most of them!).

I've just added a function which will read the properties of pre-defined viruses from a config file, so you can edit this if you want to change the properties of an existing virus, or add new ones.

You can see this file at:

https://github.com/s-andrews/virusbreak/blob/master/www/viruses.json

..and can click on the little pencil to edit it.  The values there match those on the sliders (except that the percentages are actually proportions behind the scenes).  You can edit any of the values already in there.  If you want to add a new virus to the end then just put a comma after the closing ```}``` of the previous virus and then add a new one using a template such as:

```
{
        "name" : "Influenza",
        "virulence" : 0.2,
        "incubation" : 7,
        "infection" : 4,
        "lethality" : 0.03,
        "vaccination" : 0.7,
        "quarantine" : false
}
```

The system tracks every version of every file so you can't break or lose anything by editing this file and it will be easier than having me make every change to a parameter.
