### ISSUE TITLE
Heading for the right-hand menu

### ISSUE THREAD

**Issue by AdrianListon** [s-andrews/virusbreak#16]
At the moment it is not obvious how to get to the pre-set virus options. I would suggest that the pre-set options should be the starter set, and then have a clickable button saying "Create your own virus" or the like.

**Comment by s-andrews** [comment]
That was already on my todo list. I've now implemented a basic version of this which should be visible to you.  I'll also put a third category on there for the mobile version so you can switch between viruses, properties and the actual simulation.
