### ISSUE TITLE
Note on incubation period

### ISSUE THREAD

**Issue by AdrianListon** [s-andrews/virusbreak#20]
Mostly a note to remember the data

For measles, there are 4 stages:
* non-infectious incubation = 8 days
* infectious incubation = 2 days
* infection symptomatic = 2 days
* non-infectious symptomatic = 6 days

I think the extra categories don't add much, so I have based the incubation and symptomatic lengths just based on the infectious stages. The non-infectious incubation stage would probably change the simulation a fair bit now that migration is occurring, but overall probably not worth adding.

**Comment by s-andrews** [comment]
I agree.  There's a balance between complexity and realism.  I think my ultimate limit is that I want all of the controls to be visible on screen at the same time, which limits how many different options we want to allow people to tweak.  Having three separate incubation periods to deal with is maybe going a bit too far into the complexity.
