### ISSUE TITLE
Autoreset when you pick a new virus

### ISSUE THREAD

**Issue by AdrianListon** [s-andrews/virusbreak#22]
Could you initiate an auto-reset when you pick a new virus? As it currently stands, you pick a virus and run an infection, and it uses the previous settings. The run on the chosen virus you need to pick the virus and then hit reset. It would also be good to show which virus is currently selected

**Comment by s-andrews** [comment]
I did that over the weekend so this should be OK now.  I also set it so that when you reset it introduces a single random infection so there's always something to see when you start the simulation.
