### ISSUE TITLE
Extra digit on lethality

### ISSUE THREAD

**Issue by AdrianListon** [s-andrews/virusbreak#23]
I have coded influenza and measles to have a lethality less than 1%. This works well on the simulation, but the number on the right-hand side displays "0% lethality" for measles. Could you allow it to show one extra digit, so that it becomes 0.3% lethality? We don't want to send the message that measles can't kill.

**Comment by s-andrews** [comment]
If we allow lethality to go up to 100 then this is going to be a problem since we won't have enough resolution to allow all values to be selected.  We'd need 1000px of x-space to allow a 0.1% resolution and screens aren't going to have this.  If we can limit the upper bound of lethality to something lower then this will be practical again.

**Comment by AdrianListon** [comment]
On the bars, I think it is fine to only shift by 1%. It is therefore only on the pre-set viruses, where two of the selected viruses have lethality of <1% that we need to worry. ie, we don't need to allow someone to customise a virus with lethality of <1%.

What we do need is to show the reading of 0.3% and 0.5% on the number above the moving bar, for preset viruses that have values of <1%. Does that make sense? ie, displaying the lower figure where I have circled it in the attached screenshot

![display](https://user-images.githubusercontent.com/50043996/56869607-70fed480-69fa-11e9-8ba3-574f0dce6b03.jpg)

**Comment by s-andrews** [comment]
At the moment the value you showed and the position of the bar are completely linked, so I can't get the value to show a number which the bar itself can't represent.  It might be possible to break this specifically for the selection of a virus through - I'll need to look at what that would entail.
