### ISSUE TITLE
Need real cost numbers

### ISSUE THREAD

**Issue by s-andrews** [s-andrews/virusbreak#28]
For the costing calculation we need some numbers to use.

There are 4 values we need.

1. Cost to the economy of an illness
2. Cost to the economy of a death
3. Cost to the NHS of an illness
4. Cost to the NHS of a death

If we can find something suitable to put into these I can add them to the code.

**Comment by AdrianListon** [comment]
1. Cost to the economy of an illness: £160 per symptomatic person-day
2. Cost to the economy of a death: £8.6m per death
3. Cost to the NHS of an illness: £100 per day
4. Cost to the NHS of a death: £26000 per death

**Comment by s-andrews** [comment]
Great - I'll implement those.  Having the cost be per day is nice too as it wasn't linked to the properties of the virus before.

**Comment by s-andrews** [comment]
With those values an influenza outbreak with default parameters comes out as costing around £1trillion, which is about half our GDP.  A measles outbreak comes out around £100billion.  Both of these would seem to be a bit unrealistic.

**Comment by AdrianListon** [comment]
I'm getting 19billion, both when I run the simulator and when I do the calculations manually. That is a million times lower than your number - are you sure?

**Comment by s-andrews** [comment]
I think the 1T figure is right.  It's pretty much all the economic cost of death, which you have as 8.6m.

In the basic influenza settings I get ~120,000 deaths.  That seems about right since we start with 66m people - 53% are unvaccinated, so 35m and if the infection is total then 0.5% of those die which is around 175,000.  The infections aren't always complete so 120k seems reasonable.

120,000 * 8,600,000 = 1,032,000,000,000 which is about 1 trillion (assuming we're using 1000 million as a billion, and 1000 billion as a trillion).

19billion would be 19,000,000,000 / 8,600,000 which is only about 2,200 deaths.

**Comment by AdrianListon** [comment]
That seems okay then. The 8.6m cost of a death in the UK is the UK government official costing policy. It is hard to compare to GDP, because a cost of the death is spread out over decades over lost productivity

**Comment by s-andrews** [comment]
OK, that's fine then - just wanted to check.
