### ISSUE TITLE
Hidden costs

### ISSUE THREAD

**Issue by AdrianListon** [s-andrews/virusbreak#30]
I still think that the costs would be better presented as a separate section, below the run screen, rather than as an alternative to the number of people. Ideally it would be:

(in red) Cost to NHS
(in red) Cost to economy
(in green) Cost of vaccination

Also, here I would have the same units (ie, all billions of pounds, probably) to make the comparison easier.

After that, I think we should release and let PE do their thing to promote it

**Comment by AdrianListon** [comment]
These costs work well now for the iPhone, but do not appear in the Chrome desktop version

**Comment by s-andrews** [comment]
This is because of #39 once that's fixed then the update with the new functionality will show up.
