### ISSUE TITLE
Selection of quarantine in PC desktop (chrome)

### ISSUE THREAD

**Issue by AdrianListon** [s-andrews/virusbreak#31]
While running in Chrome on a PC desktop, I can select the quarantine option, but whatever I click on with a mouse goes back to quarantine. i.e., Once quarantine is on, I cannot go back to no quarantine, and I cannot trial out the quarantine + social distancing option

**Comment by s-andrews** [comment]
This is another manifestation of #39 PWA is a cool idea but it's a royal pain when you're developing.
