### ISSUE TITLE
Selection of quarantine + social distancing on iPhone

### ISSUE THREAD

**Issue by AdrianListon** [s-andrews/virusbreak#32]
When accessing on an iPhone, I see the options for no quarantine or quarantine, but I don't have the option for quarantine + social distancing

**Comment by s-andrews** [comment]
Another #39 symptom.

**Comment by s-andrews** [comment]
I think this is just a caching issue, and on my android phone then clearing the saved data fixed it.

You should be able to test this by starting a private browsing session which shouldn't use cached data and see if it works then.

https://support.apple.com/en-gb/HT203036

If it does then you can clear your saved data. 

https://support.apple.com/lv-lv/HT201265

Now that I've turned the PWA stuff off a simple refresh should update it from now on.

**Comment by AdrianListon** [comment]
That works!
