### ISSUE TITLE
Switch button

### ISSUE THREAD

**Issue by AdrianListon** [s-andrews/virusbreak#35]
What does the "switch" button do? On chrome, there are no instructions and it doesn't seem to do anything. On the iPhone the button isn't there.

**Comment by s-andrews** [comment]
Nothing yet :-)  It will eventually switch the main display from the heatmap we have now to a graph which shows the progress of the various metrics over time so we can see the curve flattening.  I'm just working out how to make plotly graphs work to be able to add this.

The lack on button on iphone is #39 coming back to bite us again.
