### ISSUE TITLE
Embed code

### ISSUE THREAD

**Issue by AdrianListon** [s-andrews/virusbreak#37]
Is there an embed code that Sonia can use to add this to the lab website?

**Comment by s-andrews** [comment]
You can put it into an iFrame - that would let you embed it anywhere you like:

https://www.w3schools.com/html/html_iframe.asp

Something like:

```
 <iframe src="https://s-andrews.github.io/virusbreak/www/" height="1000" width="800"></iframe> 
```

Should work (change the size to whatever works for you.
