### ISSUE TITLE
Make the PWA code not cache if it's online

### ISSUE THREAD

**Issue by s-andrews** [s-andrews/virusbreak#39]
This is breaking things when we update any of the code.

I think something like this:

https://stackoverflow.com/questions/45467842/how-to-clear-cache-of-service-worker

..should do it?

**Comment by AdrianListon** [comment]
With the revision:
* all problems fixed on Chrome
* works great on Edge
* Internet Explorer is a complete mess
* Safari (iPhone) still has the problem that it can only select quarantine, even though the other options are visible

**Comment by s-andrews** [comment]
To be honest I don't think IE is ever going to work.  It's almost a completely parallel codebase to get things working there as it's so non-standard nowadays.

The bug on iPhone also seems to be the same on Android.  Not sure why that would be different to the desktop platforms but at least I've got something I can look at.

**Comment by s-andrews** [comment]
This is now completely disabled.  I might come back to it once the development is complete, but it's only relevant if you're running the thing as an offline phone app.
