### ISSUE TITLE
Quarantine message

### ISSUE THREAD

**Issue by AdrianListon** [s-andrews/virusbreak#42]
When I run the embedded version on our website: http://www.liston.babraham.ac.uk/coronavirus/

Whenever I select a virus I get the pop-op message:
An embedded page at s-andrews.github.io says
"setting no containment"

Seems to run fine

**Comment by s-andrews** [comment]
Yes, that should stop now. I put some debugging in to try to track down the mobile issue.  It was just that some files hadn't updated.  After I cleared my phone cache then the quaratine stuff started working again.

**Comment by s-andrews** [comment]
The debugging is off again so the alerts should also be gone.

**Comment by AdrianListon** [comment]
Confirmed
